# Generated by Django 5.0.6 on 2024-07-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stablexl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images/"
            ),
        ),
    ]
